/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _NativeDaemonAPI20
#define _NativeDaemonAPI20
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:
 * Method:    doDaemon
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_roam_daemon_nativ_NativeDaemonAPI20_doDaemon
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
